name: telegram_login_oidc_flutter
description: "A Flutter plugin that lets users log in to your app with Telegram. This library builds on the Telegram OpenID Connect login method introduced in 2026."
version: 0.0.4
homepage: https://github.com/wesleym/telegram_login_oidc_flutter
repository: https://github.com/wesleym/telegram_login_oidc_flutter

topics:
  - authentication
  - telegram
  - openid-connect
  - oauth
  - login

environment:
  sdk: ^3.12.0
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wesleymoy.telegram_login_oidc_flutter
        pluginClass: TelegramLoginOidcFlutterPlugin
      ios:
        pluginClass: TelegramLoginOidcFlutterPlugin
      web:
        pluginClass: TelegramLoginOidcFlutterWeb
        fileName: telegram_login_oidc_flutter_web.dart
